---
# tasks file for vault_backup
- import_tasks: install-vault.yml


- name: Take Vault snapshot with dynamic date in filename
  shell: |
    VAULT_TOKEN='{{ backup_vault_token }}' vault operator raft snapshot save -address={{ backup_vault_address }} {{ backup_base_path }}/vault_backup_{{ ansible_date_time.year }}_{{ ansible_date_time.month }}_{{ ansible_date_time.day }}.snap
  args:
    executable: /bin/bash
  become_user: root


- name: Ensure cron job for Vault snapshot is present
  when: backup_cronjob|bool
  cron:
    name: "Vault snapshot backup"
    special_time: "daily"
    job: "VAULT_TOKEN='{{ backup_vault_token }}' vault operator raft snapshot save -address={{ backup_vault_address }} {{ backup_base_path }}/vault_backup_$(date +\\%d_\\%m_\\%Y).snap"
    state: "present"
    user: "root"

